'use client'

/**
 * v10.8.0 Path B — Lazy expander for "Why Yuri would skip this" on /browse.
 *
 * Renders nothing until expanded. On first expand, fetches Opus 4.8 reasoning
 * from /api/products/curated/[id]/reasoning. Subsequent expands on the same
 * card use the cached state in this component.
 *
 * AI-First: the reasoning text is generated dynamically by Opus per
 * (user state × product). No template strings. The matched_items chips
 * shown above the prose are observational data extracted from the
 * structural Layer 1 filter, not labels generated by the AI.
 */

import { useState, useCallback } from 'react'
import { Loader2, AlertCircle, MessageCircle } from 'lucide-react'
import { supabase } from '@/lib/supabase'

/**
 * v10.8.5: extended with 'category_conflict' to mirror the server-side
 * MatchedItem.type union in product-curation.ts. v10.8.2 added category-level
 * conflict detection (Bailey's Phase 2 BHA-on-BHA / "no new actives" judgment)
 * but the UI DTO wasn't extended, so category_conflict items leaked through
 * the switch in chip rendering and displayed as bare slugs ("spot_treatment",
 * "bha") with no icon.
 *
 * The `item` field is the human-readable phrase (e.g. "no new active products
 * this phase", "BHA already at protocol cadence", "stay-the-course Phase 2
 * protocol") — what should display as primary chip text. The `matchedIngredient`
 * field is the underlying schema slug (category name or class name); useful
 * for debugging but not user-facing.
 */
export interface MatchedItemDTO {
  type: 'watch_for' | 'allergen' | 'decision_memory' | 'category_conflict'
  item: string
  matchedIngredient: string
}

export interface SkipReasoningProps {
  productId: string
  /** Initial matched_items returned with the curated list — shown as chips
   *  immediately without requiring the API roundtrip. */
  initialMatchedItems: MatchedItemDTO[]
}

interface ReasoningPayload {
  verdict: 'fits' | 'skip' | 'neutral'
  reasoning_text: string
  matched_items: MatchedItemDTO[]
  cached: boolean
  generated_at: string
  model: string
}

export default function SkipReasoning({ productId, initialMatchedItems }: SkipReasoningProps) {
  const [expanded, setExpanded] = useState(false)
  const [data, setData] = useState<ReasoningPayload | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchReasoning = useCallback(async () => {
    if (data) return
    setLoading(true)
    setError(null)
    try {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session?.access_token) {
        setError('Sign in to view Yuri\'s reasoning.')
        setLoading(false)
        return
      }
      const res = await fetch(`/api/products/curated/${encodeURIComponent(productId)}/reasoning`, {
        headers: { Authorization: `Bearer ${session.access_token}` },
        cache: 'no-store',
      })
      if (!res.ok) {
        const body = await res.json().catch(() => ({ error: 'Failed' }))
        throw new Error(body.error || 'Failed to load reasoning')
      }
      const payload = (await res.json()) as ReasoningPayload
      setData(payload)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load reasoning')
    } finally {
      setLoading(false)
    }
  }, [productId, data])

  const handleToggle = useCallback(() => {
    const next = !expanded
    setExpanded(next)
    if (next && !data && !loading) {
      fetchReasoning()
    }
  }, [expanded, data, loading, fetchReasoning])

  return (
    <div className="mt-2.5 border-t border-white/5 pt-2.5">
      {/* Matched items chips — always visible since they come with the list.
       *  v10.8.5: renders m.item (human-readable phrase) as primary text, not
       *  m.matchedIngredient (schema slug). For category_conflicts, the phrase
       *  is the source text extracted from Yuri's own decision_memory or the
       *  CATEGORY_SIGNAL_PATTERNS label — e.g. "no new active products this
       *  phase", "BHA already at protocol cadence". The slug ("spot_treatment",
       *  "bha") goes into title="" for debugging/hover. */}
      {initialMatchedItems.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mb-2">
          {initialMatchedItems.slice(0, 4).map((m, idx) => (
            <span
              key={`${m.type}-${idx}`}
              className="px-2 py-0.5 rounded-full text-[10px] bg-amber-500/15 text-amber-200 ring-1 ring-amber-400/20"
              title={`${m.type}: ${m.matchedIngredient}`}
            >
              {m.type === 'allergen' && '⚠️ '}
              {m.type === 'watch_for' && '👁 '}
              {m.type === 'decision_memory' && '📌 '}
              {m.type === 'category_conflict' && '🧪 '}
              {m.item}
            </span>
          ))}
        </div>
      )}

      <button
        onClick={handleToggle}
        className="text-[11px] text-rose-300 hover:text-rose-200 transition-colors inline-flex items-center gap-1.5"
        aria-expanded={expanded}
      >
        <MessageCircle className="w-3 h-3" />
        {expanded ? 'Hide Yuri\'s reasoning' : 'Why Yuri would skip this'}
      </button>

      {expanded && (
        <div className="mt-2 p-3 rounded-lg bg-white/[0.03] ring-1 ring-white/5">
          {loading && (
            <div className="flex items-center gap-2 text-xs text-white/50">
              <Loader2 className="w-3 h-3 animate-spin" />
              Yuri is reading the INCI against your phase…
            </div>
          )}

          {error && (
            <div className="flex items-start gap-2 text-xs text-rose-300">
              <AlertCircle className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {data && !loading && (
            <div className="space-y-2">
              <p className="text-xs leading-relaxed text-white/85 whitespace-pre-wrap">
                {data.reasoning_text}
              </p>
              <p className="text-[10px] text-white/30">
                {data.cached ? 'Cached reasoning' : 'Generated just now'} · {data.model}
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
