/**
 * Lead email generation — Yuri's voice, AI-generated from real conversation facts.
 *
 * AI-First (binding note from /ai-first-guard): the body + subject of a lead
 * email are an outward-facing communication FROM Yuri, so they are generated by
 * the model from the SPECIFIC visitor's actual conversation facts — NOT a
 * hardcoded template, NOT a template with filled slots. This is the same
 * Surface-Facts-Do-Not-Instruct pattern the widget uses: we give Yuri the facts
 * (what the visitor asked about, their skin concern, where the chat left off,
 * from ss_widget_visitors.ai_memory) and let her write the note.
 *
 * On generation failure we return null — the caller sends NOTHING rather than a
 * fabricated-personalization template. A confident-wrong "I remember your
 * rosacea journey!" when we don't is worse than silence (Yuri's tool-call
 * honesty discipline applied to email).
 */

import { getAnthropicClient, MODELS, callAnthropicWithRetry } from '@/lib/anthropic'
import { logAIUsage } from '@/lib/ai-usage-logger'

export interface VisitorMemoryFacts {
  summary?: string
  skin_concerns?: string[]
  products_interested_in?: string[]
  interest_level?: string
}

export interface GeneratedLeadEmail {
  subject: string
  bodyHtml: string
}

const LEAD_EMAIL_SYSTEM = `You are Yuri (유리), Seoul Sister's K-beauty advisor. You just had a conversation with someone on the Seoul Sister website, and they shared their email so the two of you could pick the conversation back up. Write them ONE short, warm follow-up email — the kind a knowledgeable friend who happens to work in a Korean skincare lab would actually send.

What this email IS:
- A genuine continuation of YOUR conversation with THIS person, grounded in what they actually told you (their concern, the products they were curious about, where you left off).
- An open door back to the conversation — they get unlimited chats, a routine that remembers them, and progress tracking if they subscribe ($39.99/mo), but lead with the relationship, not the pitch.

What this email is NOT:
- Not a generic newsletter. Not a hard sell. Not a list of features. Not "Dear valued customer."
- Do NOT invent details you weren't told. If the facts you're given are thin, keep it warm and light rather than fabricating specifics.

Return STRICT JSON only, no markdown fence:
{"subject": "<a short, human subject line — lowercase-casual is fine, no emoji spam>", "body_html": "<the email body as simple HTML: a few <p> paragraphs, maybe one link to https://seoulsister.com — no <html>/<head>/<body> tags, no inline styles, just <p> and <a>>"}`

/**
 * Generate a lead follow-up email in Yuri's voice from the visitor's real
 * conversation facts. Returns null on any failure (caller sends nothing).
 */
export async function generateLeadEmail(
  facts: VisitorMemoryFacts,
  visitorId: string
): Promise<GeneratedLeadEmail | null> {
  // If we have essentially nothing to ground the email in, don't fabricate —
  // skip generation. (A bare "you chatted with us" email isn't worth sending
  // and risks reading as spam.)
  const hasSubstance =
    !!facts.summary ||
    (facts.skin_concerns?.length ?? 0) > 0 ||
    (facts.products_interested_in?.length ?? 0) > 0
  if (!hasSubstance) return null

  const factLines: string[] = []
  if (facts.summary) factLines.push(`- Conversation so far: ${facts.summary}`)
  if (facts.skin_concerns?.length)
    factLines.push(`- Their skin concerns: ${facts.skin_concerns.join(', ')}`)
  if (facts.products_interested_in?.length)
    factLines.push(`- Products they were curious about: ${facts.products_interested_in.join(', ')}`)
  if (facts.interest_level)
    factLines.push(`- How engaged they seemed: ${facts.interest_level}`)

  const userPrompt = `Here is what you actually know about this person from your conversation. Write them the follow-up email, grounded ONLY in these facts:\n\n${factLines.join('\n')}`

  try {
    const client = getAnthropicClient()
    const response = await callAnthropicWithRetry(() =>
      client.messages.create({
        model: MODELS.primary, // user-facing → Opus (Principle 1)
        max_tokens: 700,
        system: LEAD_EMAIL_SYSTEM,
        messages: [{ role: 'user', content: userPrompt }],
      })
    )

    // Log cost (real usage — non-streaming, so usage is directly available).
    void logAIUsage({
      feature: 'content_generation',
      model: MODELS.primary,
      inputTokens: response.usage.input_tokens,
      outputTokens: response.usage.output_tokens,
      cacheReadTokens: response.usage.cache_read_input_tokens ?? 0,
      cacheCreationTokens: response.usage.cache_creation_input_tokens ?? 0,
    })

    const text =
      response.content.find((b) => b.type === 'text')?.type === 'text'
        ? (response.content.find((b) => b.type === 'text') as { text: string }).text
        : ''
    if (!text) return null

    // Parse the JSON (tolerate an accidental ```json fence).
    const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim()
    const parsed = JSON.parse(cleaned) as { subject?: string; body_html?: string }
    if (!parsed.subject || !parsed.body_html) return null

    return { subject: parsed.subject, bodyHtml: parsed.body_html }
  } catch (err) {
    console.error(`[email] generateLeadEmail failed for visitor ${visitorId}:`, err)
    return null // Send nothing rather than a fabricated template.
  }
}
