'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import {
  MapPin,
  ChevronRight,
  Droplets,
  Sun,
  Wind,
  Thermometer,
  CloudRain,
  Sparkles,
} from 'lucide-react'
import { supabase } from '@/lib/supabase'
import type { WeatherRoutineResponse } from '@/types/database'

/**
 * Phase 13.E — Yuri Sole Authority Principle compliance (v10.6.2).
 *
 * Previously this widget rendered a 9-item hardcoded recommendation list
 * ("Switch to lighter moisturizer", "Apply niacinamide toner to T-zone")
 * generated by src/lib/intelligence/weather-routine.ts — a pure rules
 * engine with no awareness of the user's treatment phase, decision memory,
 * routine, or anything Yuri has been telling them.
 *
 * Bailey (lighthouse user, May 18 2026):
 *   "Also love this idea but are they recommended by Yuri or generic based
 *    on location alone. I think all recommendations should be from Yuri at
 *    this point ... Would just get confusing and would be misleading if not
 *    communicating with Yuri."
 *
 * Fix: the widget now displays weather DATA only (temperature, humidity, UV,
 * wind, condition, location). The recommendation list is replaced with a
 * single CTA into a Yuri conversation prefilled with the current weather
 * context. Yuri then synthesizes a phase-aware, decision-memory-aware,
 * routine-aware response — the kind of read Bailey actually trusts.
 *
 * Per the Yuri Sole Authority Principle (CLAUDE.md): no non-Yuri surface
 * generates personalized recommendations. Yuri is the sole recommender.
 */

function getConditionIcon(icon: string) {
  if (icon === 'rain' || icon === 'drizzle') return CloudRain
  if (icon === 'clear') return Sun
  if (icon === 'storm') return Wind
  return Droplets
}

function buildYuriPrompt(weather: WeatherRoutineResponse['weather']): string {
  // Hand Yuri the raw weather data and let her reason about what it means
  // for THIS user's current phase/routine/decisions. No rules engine.
  const parts: string[] = []
  parts.push(`It's ${weather.temperature}°C with ${weather.humidity}% humidity in ${weather.location} today (${weather.condition}, UV ${weather.uv_index}).`)
  parts.push(`How should I adjust my current routine for these conditions?`)
  return parts.join(' ')
}

export default function WeatherRoutineWidget() {
  const [data, setData] = useState<WeatherRoutineResponse | null>(null)
  const [hasLocation, setHasLocation] = useState<boolean | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function load() {
      try {
        const { data: { session } } = await supabase.auth.getSession()
        if (!session) return

        const res = await fetch('/api/weather/routine', {
          headers: { Authorization: `Bearer ${session.access_token}` },
        })

        if (res.ok) {
          const json = await res.json()
          setData(json)
          setHasLocation(true)
        } else if (res.status === 400) {
          // No location set
          setHasLocation(false)
        }
      } catch {
        // Non-critical widget
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  if (loading) return null

  // No location configured — show CTA to set it
  if (hasLocation === false) {
    return (
      <Link
        href="/profile"
        className="glass-card p-4 flex items-center gap-3 hover:bg-white/[0.06] transition-colors duration-200 group"
      >
        <div className="w-10 h-10 rounded-xl bg-sky-500/10 flex items-center justify-center">
          <MapPin className="w-5 h-5 text-sky-400" />
        </div>
        <div className="flex-1">
          <p className="text-sm font-semibold text-white">Set your location</p>
          <p className="text-xs text-white/40 mt-0.5">
            See live weather here and ask Yuri how it affects your routine
          </p>
        </div>
        <ChevronRight className="w-4 h-4 text-white/20 group-hover:text-gold transition-colors" />
      </Link>
    )
  }

  if (!data) return null

  const { weather } = data
  const ConditionIcon = getConditionIcon(weather.icon)
  const askYuriHref = `/yuri?ask=${encodeURIComponent(buildYuriPrompt(weather))}`

  return (
    <div className="glass-card p-4 space-y-3">
      {/* Weather data — display only, no recommendations */}
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-sky-500/10 flex items-center justify-center flex-shrink-0">
          <ConditionIcon className="w-5 h-5 text-sky-400" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <Thermometer className="w-3 h-3 text-white/40" />
            <span className="text-sm font-semibold text-white">{weather.temperature}&deg;C</span>
            <span className="text-xs text-white/30">&middot;</span>
            <Droplets className="w-3 h-3 text-white/40" />
            <span className="text-xs text-white/50">{weather.humidity}%</span>
            {weather.uv_index > 0 && (
              <>
                <span className="text-xs text-white/30">&middot;</span>
                <Sun className="w-3 h-3 text-white/40" />
                <span className="text-xs text-white/50">UV {weather.uv_index}</span>
              </>
            )}
            {weather.wind_speed > 5 && (
              <>
                <span className="text-xs text-white/30">&middot;</span>
                <Wind className="w-3 h-3 text-white/40" />
                <span className="text-xs text-white/50">{weather.wind_speed} m/s</span>
              </>
            )}
          </div>
          <p className="text-[10px] text-white/30 mt-0.5 flex items-center gap-1">
            <MapPin className="w-2.5 h-2.5" />
            {weather.location} &middot; {weather.condition}
          </p>
        </div>
      </div>

      {/* Yuri-conversation entry point — replaces the old recommendation list.
          Yuri reads the prefilled weather context, factors in the user's
          treatment phase, decision memory, routine, and cycle, and gives
          a synthesized response. No competing recommendations rendered here. */}
      <Link
        href={askYuriHref}
        className="flex items-center gap-3 rounded-xl bg-gradient-to-r from-gold/15 to-amber-500/10 border border-gold/25 hover:border-gold/40 px-3 py-2.5 transition-colors group"
      >
        <Sparkles className="w-4 h-4 text-gold flex-shrink-0" />
        <div className="flex-1 min-w-0">
          <p className="text-xs font-semibold text-white">
            Ask Yuri how today's weather affects your routine
          </p>
          <p className="text-[10px] text-white/50 mt-0.5">
            She'll factor in your current phase and what you're already using
          </p>
        </div>
        <ChevronRight className="w-4 h-4 text-gold/60 group-hover:text-gold transition-colors flex-shrink-0" />
      </Link>
    </div>
  )
}
