-- Add AI-enriched content columns to ss_ingredients
-- Stores structured rich content generated by AI for SEO-quality ingredient pages
-- rich_content is JSONB with sections: overview, how_it_works, skin_types, usage_tips, history_origin, faq
-- Backward compatible: NULL = not enriched, page falls back to thin description

ALTER TABLE ss_ingredients
  ADD COLUMN IF NOT EXISTS rich_content JSONB,
  ADD COLUMN IF NOT EXISTS rich_content_generated_at TIMESTAMPTZ;

-- Index for sitemap priority differentiation (enriched vs thin)
CREATE INDEX IF NOT EXISTS idx_ss_ingredients_rich_content_generated
  ON ss_ingredients (rich_content_generated_at)
  WHERE rich_content_generated_at IS NOT NULL;
