-- ============================================================
-- v10.10.0 — Proactive Nudge Engine: durable memory + nudge ledger
--
-- Two tables:
--   ss_user_memory  — per-user DURABLE memory store. Corrections age out of the
--                     recent-conversation window (loadDecisionMemory reads only
--                     the 3 most recent conversations), but corrections are
--                     ground truth and must persist forever. A weekly rollup cron
--                     consolidates corrections here. (LGAAS Blueprint 79 pattern.)
--   ss_user_nudges  — the proactive-nudge ledger. One row per nudge generated.
--                     Powers spacing/cap enforcement, dashboard delivery, and
--                     observability. Channel-agnostic (push is a future adapter
--                     on the same rows).
-- ============================================================

-- ---------------------------------------------------------------
-- Durable per-user memory store
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ss_user_memory (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  -- Corrections promoted from decision_memory. Same shape as
  -- DecisionMemory.corrections[]: { topic, yuri_said, truth, category, date }.
  -- Never ages — "every correction by definition is ground truth."
  durable_corrections JSONB NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE ss_user_memory ENABLE ROW LEVEL SECURITY;

-- Service role manages (rollup cron + context loader use service client)
CREATE POLICY "Service role manages user memory"
  ON ss_user_memory FOR ALL
  USING ((SELECT auth.role()) = 'service_role');

-- Users may read their own durable memory
CREATE POLICY "Users read own durable memory"
  ON ss_user_memory FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

-- ---------------------------------------------------------------
-- Proactive nudge ledger
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ss_user_nudges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- e.g. 'open_loop', 'phase_routine_mismatch', 'cycle_timed', 'glass_skin_cadence'
  nudge_type TEXT NOT NULL,
  -- short machine reason for why this fired (for observability + dedup)
  trigger_reason TEXT NOT NULL,
  -- the Yuri-voiced message (generated by Opus 4.8)
  message TEXT NOT NULL,
  -- prefilled /yuri?ask= deep link the nudge routes to
  deep_link TEXT,
  -- which nudge number this is for the user (1/2/3 escalation ladder)
  nudge_sequence INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'surfaced', 'dismissed', 'acted')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  surfaced_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ,
  acted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_user_nudges_user_created
  ON ss_user_nudges (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_nudges_pending
  ON ss_user_nudges (user_id, status) WHERE status = 'pending';

ALTER TABLE ss_user_nudges ENABLE ROW LEVEL SECURITY;

-- Service role manages (cron writes, generation)
CREATE POLICY "Service role manages nudges"
  ON ss_user_nudges FOR ALL
  USING ((SELECT auth.role()) = 'service_role');

-- Users read their own nudges (dashboard surface)
CREATE POLICY "Users read own nudges"
  ON ss_user_nudges FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

-- Users update their own nudges (mark surfaced/dismissed/acted from dashboard)
CREATE POLICY "Users update own nudges"
  ON ss_user_nudges FOR UPDATE
  USING ((SELECT auth.uid()) = user_id);
